"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { apiClient, BusinessProfileRequest, BusinessStage } from "../../../../../lib/api";
import { ArrowRight, ChevronDown } from "../../../../../components/icons";

export default function EditProfilePage() {
  const { id } = useParams<{ id:string }>();
  const router = useRouter();
  const [form, setForm] = useState<BusinessProfileRequest | null>(null);
  const [error,setError] = useState("");
  const [busy,setBusy] = useState(false);
  useEffect(() => { apiClient.getProfile(id).then(p => setForm({ businessName:p.businessName, sector:p.sector, activity:p.activity, district:p.district, midcUnit:p.midcUnit, investmentInr:p.investmentInr, panNumber:p.panNumber || "", gstin:p.gstin || "", employees:p.employees, powerUsageKw:p.powerUsageKw, businessStage:p.businessStage, regulatoryAttributes:p.regulatoryAttributes || {} })).catch(e => setError(e instanceof Error ? e.message : "Could not load profile.")); }, [id]);
  function set<K extends keyof BusinessProfileRequest>(key:K, value:BusinessProfileRequest[K]) { setForm(current => current ? {...current,[key]:value} : current); }
  async function submit(e:FormEvent) { e.preventDefault(); if(!form) return; setBusy(true); setError(""); try { await apiClient.updateProfile(id, {...form, investmentInr:Number(form.investmentInr), employees:Number(form.employees), powerUsageKw:Number(form.powerUsageKw)}); if(typeof window !== "undefined") localStorage.setItem("anumati_last_profile", id); router.push(`/app/profiles/${id}`); } catch(e) { setError(e instanceof Error ? e.message : "Could not update profile."); } finally { setBusy(false); } }
  if(!form) return <div className="loading-state">{error || "Loading profile..."}</div>;
  return <div className="form-page"><header className="workspace-header form-header"><div><span className="eyebrow">Business regulatory twin</span><h1>Edit business state.</h1><p>Changes create a new profile version and invalidate readiness that was verified against an older state.</p></div><Link href={`/app/profiles/${id}`} className="button button-secondary">Back to profile</Link></header><form className="form-card" onSubmit={submit}>{error?<div className="form-alert">{error}</div>:null}<div className="form-section"><div><h2>Business identity</h2><p>Keep the current registered business context accurate.</p></div><div className="form-grid"><label className="field field-span-2"><span>Business name</span><input value={form.businessName} onChange={e=>set("businessName",e.target.value)} required /></label><label className="field"><span>Sector</span><input value={form.sector} onChange={e=>set("sector",e.target.value)} required /></label><label className="field"><span>Activity</span><input value={form.activity} onChange={e=>set("activity",e.target.value)} required /></label><label className="field"><span>District</span><input value={form.district} onChange={e=>set("district",e.target.value)} required /></label><label className="field"><span>Stage</span><select value={form.businessStage} onChange={e=>set("businessStage",e.target.value as BusinessStage)}><option value="IDEA">Idea</option><option value="SETUP">Setup</option><option value="OPERATING">Operating</option><option value="EXPANSION">Expansion</option></select></label></div></div><div className="form-section"><div><h2>Operating context</h2><p>Values used by applicable regulatory rules.</p></div><div className="form-grid"><label className="field"><span>Investment (INR)</span><input type="number" min="0" value={form.investmentInr} onChange={e=>set("investmentInr",Number(e.target.value))} required /></label><label className="field"><span>Employees</span><input type="number" min="0" value={form.employees} onChange={e=>set("employees",Number(e.target.value))} required /></label><label className="field"><span>Power usage (kW)</span><input type="number" min="0" step="0.01" value={form.powerUsageKw} onChange={e=>set("powerUsageKw",Number(e.target.value))} required /></label><label className="field field-check"><input type="checkbox" checked={form.midcUnit} onChange={e=>set("midcUnit",e.target.checked)} /><span>Unit is located in an MIDC area</span></label></div></div>
        <div className="form-section"><div><h2>Regulatory characteristics</h2><p>Explicit business characteristics can drive source-backed regulatory rules. They are stored as part of the versioned business state.</p></div><div className="form-grid"><label className="field"><span>Environmental / regulatory category</span><span className="select-wrap"><select value={form.regulatoryAttributes?.pollutionCategory || ""} onChange={e=>set("regulatoryAttributes", { ...form.regulatoryAttributes, pollutionCategory: e.target.value })}><option value="">Not specified</option><option value="GREEN">Green</option><option value="ORANGE">Orange</option><option value="RED">Red</option></select><ChevronDown size={16}/></span></label><label className="field field-check"><input type="checkbox" checked={form.regulatoryAttributes?.environmentalConsentRequired === "true"} onChange={e=>set("regulatoryAttributes", {...form.regulatoryAttributes, environmentalConsentRequired:e.target.checked?"true":"false"})} /><span>Environmental consent may be relevant</span></label><label className="field field-check"><input type="checkbox" checked={form.regulatoryAttributes?.hazardousProcess === "true"} onChange={e=>set("regulatoryAttributes", {...form.regulatoryAttributes, hazardousProcess:e.target.checked?"true":"false"})} /><span>Hazardous process characteristic</span></label></div></div>
<div className="form-section"><div><h2>Identifiers</h2><p>Keep identifiers aligned with source documents.</p></div><div className="form-grid"><label className="field"><span>PAN</span><input maxLength={10} value={form.panNumber || ""} onChange={e=>set("panNumber",e.target.value.toUpperCase())} /></label><label className="field"><span>GSTIN</span><input maxLength={15} value={form.gstin || ""} onChange={e=>set("gstin",e.target.value.toUpperCase())} /></label></div></div><div className="form-footer"><p>After saving, rerun regulatory analysis and document validation for the new business version.</p><button className="button button-primary" disabled={busy}>{busy ? "Saving…" : "Save new version"}<ArrowRight size={17}/></button></div></form></div>;
}
