package in.anumati.platform.incentive;
import in.anumati.platform.audit.AuditService; import in.anumati.platform.business.BusinessProfile; import in.anumati.platform.business.BusinessProfileService; import in.anumati.platform.regulatory.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;
@Service public class IncentiveService {private final IncentiveSchemeRepository schemes;private final IncentiveConditionRepository conditions;private final BusinessProfileService profiles;private final AuditService audit;public IncentiveService(IncentiveSchemeRepository s,IncentiveConditionRepository c,BusinessProfileService p,AuditService a){schemes=s;conditions=c;profiles=p;audit=a;}
 @Transactional public IncentiveScheme create(IncentiveSchemeRequest req,String actor,RegulatorySourceRepository sourceRepo){var source=sourceRepo.findById(req.sourceId()).orElseThrow(()->new IllegalArgumentException("Source not found"));if(source.getVerificationStatus()!=SourceVerificationStatus.VERIFIED)throw new IllegalArgumentException("Incentive source must be verified");IncentiveScheme scheme=schemes.save(new IncentiveScheme(req.code(),req.name(),req.authority(),req.benefitSummary(),req.applicationUrl(),source,req.active()));for(var c:req.conditions())conditions.save(new IncentiveCondition(scheme,c.field(),c.operator(),c.valueType(),c.value(),c.sequenceNumber()));audit.record(actor,"INCENTIVE_SCHEME_CREATED","IncentiveScheme",scheme.getId(),Map.of("code",scheme.getCode()));return scheme;}

    @Transactional(readOnly=true) public List<IncentiveMatchResponse> matches(UUID profileId,String actor){BusinessProfile p=profiles.getForActor(profileId,actor);List<IncentiveMatchResponse> out=new ArrayList<>();for(IncentiveScheme s:schemes.findByActiveTrue()){if(s.getSource().getVerificationStatus()!=SourceVerificationStatus.VERIFIED) continue; List<IncentiveCondition> cs=conditions.findByScheme_IdOrderBySequenceNumberAsc(s.getId());boolean ok=true;List<String> reasons=new ArrayList<>();for(IncentiveCondition c:cs){String actual=valueFor(p,c.getField());if(!matches(actual,c.getValue(),c.getOperator(),c.getValueType())){ok=false;break;}reasons.add(c.getField().name()+" "+c.getOperator().name()+" "+c.getValue());}if(ok)out.add(new IncentiveMatchResponse(s.getId(),s.getCode(),s.getName(),s.getAuthority(),s.getBenefitSummary(),s.getApplicationUrl(),s.getSource().getId(),s.getSource().getTitle(),s.getSource().getUrl(),cs.isEmpty()?"No additional eligibility conditions were configured":"Your profile matched the configured eligibility conditions",reasons));}return out;}
 private static String valueFor(BusinessProfile p,ConditionField f){return switch(f){case SECTOR->p.getSector();case ACTIVITY->p.getActivity();case DISTRICT->p.getDistrict();case MIDC_UNIT->String.valueOf(p.getMidcUnit());case INVESTMENT_INR->p.getInvestmentInr().toPlainString();case EMPLOYEES->p.getEmployees().toString();case POWER_USAGE_KW->p.getPowerUsageKw().toPlainString();case BUSINESS_STAGE->p.getBusinessStage().name();default->throw new IllegalArgumentException("Unsupported field: "+f);};}
 private static boolean matches(String actual,String expected,ConditionOperator op,ValueType vt){if(vt==ValueType.NUMBER){BigDecimal a=new BigDecimal(actual),b=new BigDecimal(expected);int c=a.compareTo(b);return switch(op){case EQ->c==0;case NEQ->c!=0;case GT->c>0;case GTE->c>=0;case LT->c<0;case LTE->c<=0;default->false;};}if(vt==ValueType.BOOLEAN){boolean a=Boolean.parseBoolean(actual),b=Boolean.parseBoolean(expected);return switch(op){case EQ->a==b;case NEQ->a!=b;default->false;};}if(op==ConditionOperator.IN||op==ConditionOperator.NOT_IN){Set<String> vals=new HashSet<>(Arrays.asList(expected.split(",")));boolean hit=vals.contains(actual);return op==ConditionOperator.IN?hit:!hit;}return switch(op){case EQ->actual.equalsIgnoreCase(expected);case NEQ->!actual.equalsIgnoreCase(expected);default->false;};}
}
