package in.anumati.platform.renewal; import in.anumati.platform.application.*; import in.anumati.platform.application.events.ApplicationDecisionRecordedEvent; import org.springframework.context.event.EventListener; import in.anumati.platform.audit.AuditService; import in.anumati.platform.business.BusinessProfileService; import in.anumati.platform.regulatory.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class RenewalService {private final RenewalRepository repo; private final ApplicationRepository apps; private final BusinessProfileService profiles; private final RegulatorySourceRepository sources; private final AuditService audit; public RenewalService(RenewalRepository r,ApplicationRepository a,BusinessProfileService p,RegulatorySourceRepository s,AuditService x){repo=r;apps=a;profiles=p;sources=s;audit=x;}
 @EventListener
 @Transactional
 public void onDecisionRecorded(ApplicationDecisionRecordedEvent event){
     if(event.outcome()!=DecisionOutcome.APPROVED || event.validUntil()==null) return;
     ApplicationRecord app=apps.findById(event.applicationId()).orElseThrow(()->new IllegalArgumentException("Application not found: "+event.applicationId()));
     createFromDecision(app,event.validFrom(),event.validUntil(),event.sourceId(),30,event.actor());
 }

 @Transactional public RenewalResponse create(RenewalRequest req,String actor,boolean departmentActor){if(req.sourceId()==null) throw new IllegalArgumentException("A manually created renewal requires an authoritative source"); if(!departmentActor) {var app=apps.findById(req.applicationId()).orElseThrow();profiles.getForActor(app.getBusinessProfile().getId(),actor);} var app=apps.findById(req.applicationId()).orElseThrow(()->new IllegalArgumentException("Application not found")); if(app.getStatus()!=ApplicationStatus.APPROVED) throw new IllegalArgumentException("Renewal can only be created for an approved application"); if(repo.findByApplication_Id(app.getId()).isPresent()) throw new IllegalArgumentException("Renewal already exists for this application"); RegulatorySource source=null; if(req.sourceId()!=null){source=sources.findById(req.sourceId()).orElseThrow(()->new IllegalArgumentException("Source not found")); if(source.getVerificationStatus()!=SourceVerificationStatus.VERIFIED) throw new IllegalArgumentException("Renewal source must be verified");} RenewalRecord r=repo.save(new RenewalRecord(app,req.validFrom(),req.validUntil(),req.reminderDays(),source)); audit.record(actor,"RENEWAL_CREATED","Renewal",r.getId(),Map.of("applicationId",app.getId())); return RenewalResponse.from(r);}
 @Transactional public RenewalResponse createFromDecision(ApplicationRecord app, java.time.LocalDate validFrom, java.time.LocalDate validUntil, UUID sourceId, int reminderDays, String actor){ if(validUntil==null) throw new IllegalArgumentException("validUntil is required to create a renewal record"); if(validFrom!=null && validUntil.isBefore(validFrom)) throw new IllegalArgumentException("validUntil must be on or after validFrom"); if(validUntil.isBefore(java.time.LocalDate.now())) throw new IllegalArgumentException("validUntil cannot be in the past"); if(repo.findByApplication_Id(app.getId()).isPresent()) return RenewalResponse.from(repo.findByApplication_Id(app.getId()).orElseThrow()); RegulatorySource source=null; if(sourceId!=null){source=sources.findById(sourceId).orElseThrow(()->new IllegalArgumentException("Source not found")); if(source.getVerificationStatus()!=SourceVerificationStatus.VERIFIED) throw new IllegalArgumentException("Renewal source must be verified");} RenewalRecord r=repo.save(new RenewalRecord(app,validFrom,validUntil,reminderDays,source)); audit.record(actor,"RENEWAL_CREATED","Renewal",r.getId(),Map.of("applicationId",app.getId())); return RenewalResponse.from(r);}

 @Transactional(readOnly=true) public List<RenewalResponse> forBusiness(UUID profileId,String actor){profiles.getForActor(profileId,actor); return repo.findByBusinessProfile_IdOrderByValidUntilAsc(profileId).stream().peek(RenewalRecord::refresh).map(RenewalResponse::from).toList();}
 @Transactional public RenewalResponse start(UUID id,String actor,boolean dept){RenewalRecord r=repo.findById(id).orElseThrow(()->new IllegalArgumentException("Renewal not found")); if(!dept)profiles.getForActor(r.getBusinessProfile().getId(),actor); if(r.getStatus()==RenewalStatus.COMPLETED) throw new IllegalArgumentException("Completed renewal cannot be started again"); if(r.getStatus()==RenewalStatus.IN_PROGRESS) throw new IllegalArgumentException("Renewal is already in progress"); r.markInProgress();audit.record(actor,"RENEWAL_STARTED","Renewal",id,Map.of());return RenewalResponse.from(r);}
 @Transactional public RenewalResponse complete(UUID id,String actor,boolean dept){RenewalRecord r=repo.findById(id).orElseThrow(()->new IllegalArgumentException("Renewal not found"));if(!dept)throw new AccessDeniedException("Department role required");r.markCompleted();audit.record(actor,"RENEWAL_COMPLETED","Renewal",id,Map.of());return RenewalResponse.from(r);}
 @Transactional(readOnly=true) public List<RenewalResponse> all(){return repo.findAllByOrderByValidUntilAsc().stream().peek(RenewalRecord::refresh).map(RenewalResponse::from).toList();}
}
