package in.anumati.platform.renewal; import in.anumati.platform.application.ApplicationRecord; import in.anumati.platform.business.BusinessProfile; import in.anumati.platform.regulatory.Approval; import in.anumati.platform.regulatory.RegulatorySource; import jakarta.persistence.*; import java.time.*; import java.util.*;
@Entity @Table(name="renewals") public class RenewalRecord { @Id private UUID id; @OneToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="application_id",nullable=false,unique=true) private ApplicationRecord application; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="business_profile_id",nullable=false) private BusinessProfile businessProfile; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="approval_id",nullable=false) private Approval approval; private LocalDate validFrom; @Column(nullable=false) private LocalDate validUntil; @Column(nullable=false) private int reminderDays; @Enumerated(EnumType.STRING) @Column(nullable=false,length=30) private RenewalStatus status; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="source_id") private RegulatorySource source; @Column(nullable=false) private Instant createdAt; @Column(nullable=false) private Instant updatedAt; protected RenewalRecord(){} public RenewalRecord(ApplicationRecord a,LocalDate from,LocalDate until,int reminder,RegulatorySource s){id=UUID.randomUUID();application=a;businessProfile=a.getBusinessProfile();approval=a.getApproval();validFrom=from;validUntil=until;reminderDays=reminder;source=s;createdAt=Instant.now();updatedAt=createdAt;refresh();} public void refresh(){
        if (status == RenewalStatus.COMPLETED || status == RenewalStatus.IN_PROGRESS) return;
        LocalDate today=LocalDate.now();
        if(validUntil.isBefore(today)) status=RenewalStatus.EXPIRED;
        else if(!today.isAfter(validUntil.minusDays(reminderDays))) status=RenewalStatus.DUE;
        else status=RenewalStatus.UPCOMING;
        updatedAt=Instant.now();
    } public void markInProgress(){status=RenewalStatus.IN_PROGRESS;updatedAt=Instant.now();} public void markCompleted(){status=RenewalStatus.COMPLETED;updatedAt=Instant.now();} public UUID getId(){return id;} public ApplicationRecord getApplication(){return application;} public BusinessProfile getBusinessProfile(){return businessProfile;} public Approval getApproval(){return approval;} public LocalDate getValidFrom(){return validFrom;} public LocalDate getValidUntil(){return validUntil;} public int getReminderDays(){return reminderDays;} public RenewalStatus getStatus(){return status;} public RegulatorySource getSource(){return source;} public Instant getCreatedAt(){return createdAt;} public Instant getUpdatedAt(){return updatedAt;} }
